version: '3.7'
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    working_dir: /opt/ansible
    volumes:
      - ${PWD}/../:/opt/ansible
  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    working_dir: /opt/ansible
    volumes:
      - ${PWD}/../:/opt/ansible
