version: '3.5'
services:
  unit:
    build:
      context: ${PWD}/../
      dockerfile: Dockerfile.test
      target: unit
    container_name: unitest
    volumes:
      - ${PWD}/artifact/coverage:/opt/app/coverage
